### ISSUE TITLE
Persistence

### ISSUE THREAD

**Issue by BarnumD** [colinmollenhour/mariadb-galera-swarm#1]
How do you deal with data persistence?  For instance, if the docker service and/or container goes away (docker service rm) where does the data live?  How does the cluster recover?

**Comment by colinmollenhour** [comment]
If you specify the volume in `docker service create` then it would be persisted at whatever source you specified. However, I don't think you should ever need to `docker service rm` unless you want to tear down the cluster since there is an update command.
