### ISSUE TITLE
Galera crash

### ISSUE THREAD

**Issue by viki-v** [colinmollenhour/mariadb-galera-swarm#102]
Hello Sir,

I have implemented this Galera swarm in production, It has been crashed and lost production data

please help me restore the data 

when checked the logs the MySQL files are been removed, is there anyway restoration..?

**Comment by colinmollenhour** [comment]
Hi @viki-v I'm sorry to hear about the troubles. Operating a Galera cluster is definitely a task for an expert and I cannot offer help beyond what this code project offers. I would recommend reading the relevant sections of this guide to get a general idea about how to recover: [Crash Recovery](https://www.percona.com/doc/percona-xtradb-cluster/LATEST/howtos/crash-recovery.html). This guide was used as a basis for creating this container image and some of the scenarios are automatic and some require manual intervention.
MariaDb and Percona both offer paid support as well.

**Comment by colinmollenhour** [comment]
Also make sure you check the README of this project regarding the flag files, often times shutting down all nodes and then starting one with the new/cluster flag file is the quickest way to get the cluster back (the other nodes will have to do a full SST): https://github.com/colinmollenhour/mariadb-galera-swarm#flag-files
