### ISSUE TITLE
no external connection at mysql

### ISSUE THREAD

**Issue by arielesp** [colinmollenhour/mariadb-galera-swarm#103]
Hi
the containers start but I cant connect to mysql out of container ... 
its sounds like no opened ports .. or non exists
could you help me?

I tried with another image, like percona oficial, and worked fine. But I would like to use this

thanks

**Comment by colinmollenhour** [comment]
The 3306 port is exposed the same way as any other port but it is possible the server isn't starting due to the Galera setup steps, please check the server logs through `docker logs` and go from there.
