### ISSUE TITLE
Will this project ever be updated?

### ISSUE THREAD

**Issue by miberecz** [colinmollenhour/mariadb-galera-swarm#108]
I can see there is no now commit since 2 years here. Will this be ever updated to use 10.6 or recent mariadb?
Is there a point to invest this into our environment? I do not seem to found any usable project specifically wrote for Docker Swarm besides this, but 10.4 will lose support soon.

**Comment by colinmollenhour** [comment]
There may be minor differences in 10.6 that break something but most of it should still work. If you want to test it and fix or report issues I'd be happy to inspect and merge a PR.

**Comment by colinmollenhour** [comment]
I did some light testing with 10.4 through 10.8 and everything appears to be working. New images built and pushed.

**Comment by fannyfan414** [comment]
> I did some light testing with 10.4 through 10.8 and everything appears to be working. New images built and pushed.

Awesome work, thanks!

Can you upgrade to mariadb 10.11 (it’s announced as LTS)?

**Comment by colinmollenhour** [comment]
@fannyfan414 I just pushed 10.11. Also updated 10.3-10.8 and removed 10.2 from the repo.
