### ISSUE TITLE
The seed instance of version 10.11.6-2023-12-09 reports an error in initializing the database

### ISSUE THREAD

**Issue by zhuqinghua** [colinmollenhour/mariadb-galera-swarm#116]
The error message is as follows:
<img width="676" alt="image" src="https://github.com/user-attachments/assets/2314fab4-7c78-4eab-91e4-435e2432d5ce">

When I entered the container, I found that /usr/bin/my_print_defaults did exist.
<img width="934" alt="image" src="https://github.com/user-attachments/assets/0c9c2ffb-42d1-405d-b6ee-0c3f7746e581">

thanks

**Comment by colinmollenhour** [comment]
Thanks for the report. Fixed in [e4332b9](https://github.com/colinmollenhour/mariadb-galera-swarm/commit/e4332b9f72ae2dc4f946ff962fa764cb5b66662e)
 ·
