### ISSUE TITLE
Where are the changes used to build the latest docker images on https://hub.docker.com/r/colinmollenhour/mariadb-galera-swarm?

### ISSUE THREAD

**Issue by cherbst** [colinmollenhour/mariadb-galera-swarm#117]

**Comment by cherbst** [comment]
I'd like to submit a PR to fix a problem with the latest version

**Comment by colinmollenhour** [comment]
I'm not sure what you mean by changes? Do you mean the [commits](https://github.com/colinmollenhour/mariadb-galera-swarm/commits/master/)?

Currently the images are manually built and pushed, but I'd be happy to move that to GitHub Actions.

**Comment by cherbst** [comment]
Well the latest images to https://hub.docker.com/r/colinmollenhour/mariadb-galera-swarm/ are pushed 3 month ago and the file `mysqld.sh` they contain differs from the one in this repo. It also contains an error I'd like to fix.

**Comment by colinmollenhour** [comment]
Ahh, right you are! Sorry about that, looks like I made some changes and built and pushed the images but did not commit and push the source. I just pushed what I had in the working copy which should be what was in Docker Hub.
