### ISSUE TITLE
Change FROM mariadb:10.1.22 to FROM mariadb:10.1

### ISSUE THREAD

**Issue by cpjolly** [colinmollenhour/mariadb-galera-swarm#19]
mariadb:10.1.23 has been released, so 10.1.22 is now obsolete. Is there some reason to refer to a specific version, such as 10.1.22, rather than the latest 10.1 version ? If not, can we change the Dockerfile to be

FROM mariadb:10.1

**Comment by colinmollenhour** [comment]
Probably just being paranoid about breaking updates.. Changed.

**Comment by cpjolly** [comment]
Many thanks - I totally agree with being paranoid about breaking updates, but 10.1 is pretty mature at this point, so it seems an acceptable risk to take. Probably for 10.2 a different approach will make sense - perhaps a set of release tags ?
