### ISSUE TITLE
question about the bootstraping

### ISSUE THREAD

**Issue by zhjchen** [colinmollenhour/mariadb-galera-swarm#26]
~~~~
$ docker stack deploy -c docker-compose.yml galera
$ docker service ls
(wait for `galera_seed` to be healthy)
$ docker service scale galera_node=2
(wait for both `galera_node` instances to be healthy)
$ docker service scale galera_seed=0
~~~~

Why set the galera_seed to 0 in the end ?

**Comment by colinmollenhour** [comment]
Because the seed is for starting a new cluster and if it gets rebooted somehow you don't want it starting a new cluster, you want the cluster to be recovered which is done only for the "node" instances.
