### ISSUE TITLE
How to get back when all node down

### ISSUE THREAD

**Issue by zhjchen** [colinmollenhour/mariadb-galera-swarm#27]
Running two galera_node in docker swarm, set galera_node to use host directories. So the data is persistent. 

However when both galera_node containers went down, need to start galera_seed to initialize new cluster. galera_seeds was intentionally down, So galera_seed does not have latest data. 

When the galera_nodes join the new cluster, they sync data with galera_seed, so galera_node lost the latest data. Any suggestion ?

**Comment by colinmollenhour** [comment]
You should replace the galera "seed" with a "node" which uses the same data volume so that they are one and the same.
