### ISSUE TITLE
Upgrade MariaDB to v10.2

### ISSUE THREAD

**Issue by kujiy** [colinmollenhour/mariadb-galera-swarm#28]
Hi, thank you for the excellent project.
I'm planning to start using galera and hope this image helps me. I'd like to start from the latest MariaDB. Does MariaDB 10.2 have some difficulties?

**Comment by colinmollenhour** [comment]
I don't know, perhaps give it a go and let us know! :)

I wouldn't be at all surprised if a few options have changed names, been deprecated, new features added, etc..

**Comment by colinmollenhour** [comment]
Actually it looks like it has been a while since Galera has released an update so I think as of now the latest 10.1 and 10.2 are using the same version of Galera so there may not be any issues.

**Comment by kujiy** [comment]
Thanks. I'll try next week if I have time, ICBW. I knew Galera had own version now, I'm a very beginner. Please don't expect too much!

**Comment by cpjolly** [comment]
If anyone is interested, in the fork https://github.com/cpjolly/mariadb-galera-swarm I've created update.sh and Dockerfile.template, to generate version folders, similar to the structure in https://github.com/docker-library/mariadb.

@colinmollenhour - let me know if you'd like me to make a pull request.

**Comment by colinmollenhour** [comment]
Thanks guys I started maintaining a second Dockerfile for 10.1 and 10.2 will be in the main Dockerfile now. 10.1 is pegged at 10.1.31 for now until the bugs are fixed upstream so the patches can be removed. I believe 10.1 to be stable now. I still haven't tested 10.2 myself but it should work as well.
