### ISSUE TITLE
Backup method

### ISSUE THREAD

**Issue by ariselseng** [colinmollenhour/mariadb-galera-swarm#35]
Hi,
It could be great to have a way in this image to do database dumps. or perhaps this is already possible?

**Comment by colinmollenhour** [comment]
The tools needed to do various types of backups are all in the image, just call them with docker exec or docker run or connect to the database remotely. I'd recommend xtrabackup, which is included in the image (percona-toolkit). Here is a wrapper script that is not included in the image but you could add it in yourself in a new image or with "docker cp" or just add it to your data directory assuming it is bind-mounted to a volume or host directory.

https://gist.github.com/colinmollenhour/16d8d92d2ecddddcfa7f0a991d11e830

**Comment by ariselseng** [comment]
Thank you so much for that.
