### ISSUE TITLE
Cluster fails to start

### ISSUE THREAD

**Issue by rbnor** [colinmollenhour/mariadb-galera-swarm#37]
cluster does not start when deploying stack to docker swarm.

**Comment by colinmollenhour** [comment]
There is not enough information here to address your issue.

**Comment by rbnor** [comment]
start.sh: Trapped error on line 113

The seed never starts

**Comment by rbnor** [comment]
galera_seed.1.zs2nzxqhxrpd@docker-2    | start.sh: Trapped error on line 113

**Comment by colinmollenhour** [comment]
What are you using for NODE_ADDRESS? What is the output of "getent hosts $(hostname)" from within the container.

**Comment by rbnor** [comment]
- NODE_ADDRESS=^10.0.0.*
It does not start, so I can't really exec into the container.

**Comment by colinmollenhour** [comment]
I simply can't help you with so little info.
