### ISSUE TITLE
docker stack deploy -c docker-compose.yml galera fails

### ISSUE THREAD

**Issue by sfarrell5123** [colinmollenhour/mariadb-galera-swarm#52]
when I run  'docker stack deploy -c docker-compose.yml galera'

from your examples/swarm

I get this error :

name Additional property name is not allowed

docker compose --version
Docker version 18.06.1-ce, build e68fc7a

I read you can get that error also if there is an illegal character

It seems it might be version related also

**Comment by sfarrell5123** [comment]
I changed it to this


volumes:
  vol-name:
    external:
      name: '{{.Service.Name}}-{{.Task.Slot}}-data'

volumes:
  mysql-data:
    driver: local


not sure if it's as intended or not, but at least it executed

**Comment by sfarrell5123** [comment]
might just need version 3.4 or newer at the top of the file

**Comment by colinmollenhour** [comment]
Merged #54
