### ISSUE TITLE
Feature-Request: Upgrade to support encryption

### ISSUE THREAD

**Issue by flybyray** [colinmollenhour/mariadb-galera-swarm#57]
Just some hints.

"MariaDB Backup is based on Percona XtraBackup 2.3.8 and therefore provides similar functionality plus:"
https://mariadb.com/kb/en/library/mariadb-backup-overview/#using-mariadb-backup

https://mariadb.com/kb/en/library/data-at-rest-encryption/#limitations
"Percona XtraBackup cannot back up instances that use encrypted InnoDB. However, MariaDB's fork, MariaDB Backup, can back up encrypted instances."

"MariaDB Backup is provided as part of MariaDB Server starting with MariaDB 10.1.23 and MariaDB 10.2.7."
https://mariadb.com/kb/en/library/mariadb-backup-overview/

see: https://github.com/MariaDB/server/blob/5abc79dd7ab2fccb4b05ca38a512ec816d2f8e52/mysql-test/suite/galera/t/galera_sst_mariabackup.cnf

**Comment by colinmollenhour** [comment]
Thanks for the notice, it seems it should be pretty straightforward to switch from xtrabackup to mariabackup and it looks like the Dockerfile contains commands to install mariabackup so perhaps it just needs a newer version to be built... It appears that mariabackup should be basically a direct drop-in for xtrabackup-v2, is that correct?

**Comment by flybyray** [comment]
> It appears that mariabackup should be basically a direct drop-in for xtrabackup-v2, is that correct?

For me it seems like that. I am not sure if there are other enhencements or drawbacks. But for sure it  is the only possible way actually to have physical backups of encrypted database storage (not just the logical mysqldump backups).
I think mariadb foundation wants to take control over such important and advanced things. i did not know before that microsoft is a platinum sponsor of mariadb. https://mariadb.org/about/supporters/ :+1:

**Comment by colinmollenhour** [comment]
I added a build for 10.3 and made mariabackup the default SST method. Also added a test script which proves a basic seed-node sync.

**Comment by diabelb** [comment]
I can confirm the same bug on docker 20.10.20. It's still not fixed.
