### ISSUE TITLE
guide for the dummies

### ISSUE THREAD

**Issue by eleaner** [colinmollenhour/mariadb-galera-swarm#60]
Hi,

I suppose I try to do shortcuts setting up cluster without really understanding how databases or even docker work. 
Hence probably stupid questions.

I used docker-compose.yml in the examples and followed the readme
I have three galera_nodes running on workers in my swarm
And that's pretty much it.

How do I access my database?
I assumed my credentials sit in .secrets
shall I run mysql from the swarm manager? I have seen another query about "localhost"
What if I already have database running on swarm manager? should I map ports somehow?
I tried to run mariadb-client on one of the nodes and got
`ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock'`
I am completely lost

**Comment by eleaner** [comment]
ok. so for starter, my cluster does not seem to work really
I only have three nodes that are restarting periodically

how could I try to analyse what is failing?

**Comment by colinmollenhour** [comment]
I think you have a lot of questions that aren't specific to this container image and so you should first get familiar with running a single node and perhaps seek some help on some public forum like a slack channel. Unfortunately I don't have time to write a full guide. :) glty
