### ISSUE TITLE
Nodes can't join the "seed" container 

### ISSUE THREAD

**Issue by w7089** [colinmollenhour/mariadb-galera-swarm#7]
Hi,
After running 
`docker service create --name galera-seed --replicas 1 -e  XTRABACKUP_PASSWORD=test seed`
`docker service create --name galera --replicas 2  -e  XTRABACKUP_PASSWORD=test node tasks.galera-seed,tasks.galera`

I see that 2 docker galera containers are crashing after a minute after failing to reach "healthy" status. 
And there's error at the log of the crashed containers.

> {"log":"ERROR 1045 (28000): Access denied for user 'system'@'127.0.0.1' (using password: YES)\n","stream":"stderr","time":"2017-01-01T18:38:43.485726233Z"}
{"log":"start.sh: Trapped error on line 198\n","stream":"stdout","time":"2017-01-01T18:38:43.486807412Z"}

The first service is up and running. Can you tell me what i might be doing wrong, please?

**Comment by colinmollenhour** [comment]
Please see #5. I suppose the README should be updated with this info..

**Comment by w7089** [comment]
Hi, thanks, i fear, i don't fully understand the problem and it's solution. My db is empty, this error happens during the initial cluster bootstrap.

**Comment by colinmollenhour** [comment]
Line 198 is in the trapped shutdown signal handler so I suspect docker is sending the shutdown signal due to unhealthy status so playing with the swarm options might help. I think I'd have to see the full logs to be helpful.

**Comment by colinmollenhour** [comment]
There was a bug that I found where the seed node was starting with the wrong command line arguments. Not sure if this was your issue or not.
