### ISSUE TITLE
Typo in Dockerfile

### ISSUE THREAD

**Issue by rjsocha** [colinmollenhour/mariadb-galera-swarm#78]
I think this is a typo in Dockerfile:

```
    && rm -rf /tmp/* /var/cache/apk/* /var/lib/apt/lists/*
```
Correct folder should be /var/cache/apt not /var/cache/apk.

Or better (more debian way:):
```
    && apt-get clean all && rm -rf /tmp/* /var/lib/apt/lists/*
```

**Comment by JKJameson** [comment]
Well spotted. I created PR #93 for you
