### ISSUE TITLE
WSREP: Process completed with error

### ISSUE THREAD

**Issue by alphaDev23** [colinmollenhour/mariadb-galera-swarm#80]
The error below is in the node logs (along with the surrounding log entries).  Is this an issue and how should this be resolved?

WSREP_SST: [INFO] Cleaning up fifo file /tmp/mysql-console/fifo (20190704 03:45:42.469),
rm: cannot remove '/tmp/mysql-console/fifo': Permission denied
2019-07-04  3:45:42 0 [ERROR] WSREP: Process completed with error: wsrep_sst_mariabackup --role 'joiner' --address '10.0.21.13' --datadir '/var/lib/mysql/'   --parent '45'  ''  '': 1 (Operation not permitted),
2019-07-04  3:45:42 0 [Note] WSREP: SST complete, seqno: 0

**Comment by colinmollenhour** [comment]
This is actually intentional: https://github.com/colinmollenhour/mariadb-galera-swarm/blob/master/start.sh#L376

I don't think it is an issue, but I suppose that could change if it caused the mariabackup script to exit prematurely.

**Comment by colinmollenhour** [comment]
I've modified the wsrep_sst_mariabackup script via the Dockerfile to prevent this error.
