### ISSUE TITLE
Swarm automatic cluster creation

### ISSUE THREAD

**Issue by alphaDev23** [colinmollenhour/mariadb-galera-swarm#84]
Adding the shell code below appears to allow swarm users the ability to automatically create the cluster without having to manually scale the seed and the cluster.  The node service can specify the total number of replicas in the service definition.  The cluster will be created and the seed will automatically be created after all the nodes have joined and the cluster is synced.  Note, I'm not a Galera expert so there may be a more efficient way to accomplish the same.  Suggestions are welcome.

I have added the following environment variables to the seed:
    - IS_SEED=true
    - SKIP_UPGRADES=1
    - MYSQL_ROOT_SOCKET_AUTH=0
    - NODE_REPLICAS=<integer of total number of nodes + seed>
    - CLUSTER_NAME=<unique name.  

Also, the following needs to be added to the seed service definition:
```
    deploy:
      restart_policy: 
        condition: none
```

The following code is added after the 'gosu mysql mysqld.sh...' line in start.sh but prior to 'wait $! || true':

```
if [[ $IS_SEED = "true" ]] ; then
	cluster_size=1
	while [ "$cluster_size" -lt "$NODE_REPLICAS" ] ; do   
	    cluster_size=`mysql -uroot -p$MYSQL_ROOT_PASSWORD information_schema -N -e "select VARIABLE_VALUE from GLOBAL_STATUS where VARIABLE_NAME='wsrep_cluster_size';"`	
	    echo "cluster size: $cluster_size"
		sleep 10
	done
	
	local_state=""
	while [ "$local_state" != "Synced" ] ; do   
	    local_state=`mysql -uroot -p$MYSQL_ROOT_PASSWORD information_schema -N -e "select VARIABLE_VALUE from GLOBAL_STATUS where VARIABLE_NAME='wsrep_local_state_comment';"`	
	    echo "local state: $local_state"
		sleep 10
	done
        # The following sleep command may possibly be reduced but adding it appears to ensure that the state transfers are completed prior to the seed shutdown
        sleep 120
	shutdown
fi
```

**Comment by colinmollenhour** [comment]
So does this method assume that you will actually run N+1 cluster members? One issue with that is that if you only have N physical nodes it requires an additional node temporarily or double the disk space on one node which for a large database could be an issue. Manually starting the seed and rebooting it as a node allows the seed node to not have to be duplicated.

**Comment by alphaDev23** [comment]
The method assumes only N cluster members.  For a majority of databases, disk space should not be an issue and it is assumed that the user has appropriately sized the swarm nodes.  Additionally, since volumes can be separately mounted, it does not require that the swarm node itself contain the disk space needed for the database.  For the clusters that we deploy, the seed is constrained to the master and one of the node containers is also started on the container. 

I have now tested this with a number of different stacks and it appears to be running without issue.  The above dramatically simplifies deployment because the stack can be deployed without any manual intervention.

A solution to offer both options, the above and the current, would be to incorporate an environment variable in the code which would conditionally use the above suggested deployment implementation.

**Comment by colinmollenhour** [comment]
Ok, perhaps I don't fully understand it still. Would you mind putting it into a pull request for direct review? Thanks for your contributions!

**Comment by alphaDev23** [comment]
I would rather spend time ensuring that you understand the code because a pull request, especially given its confined nature, will not answer any questions/concern.  What do you not fully understand and maybe I can answer your questions.

Happy to contribute back to your fantastic work.

**Comment by colinmollenhour** [comment]
Mainly what the correct parameters are for the `docker-compose.yml` file and the steps for creating a cluster after this update. How do you prevent the Nth node from starting until the seed is shut down?

**Comment by alphaDev23** [comment]
Why is that needed?  In a 3 node + seed stack definition, all the nodes join and are synced creating a 4 node cluster after which the seed is shut down leaving the desired 3 node cluster.

**Comment by colinmollenhour** [comment]
What if your nodes are not so easily created/destroyed? E.g. high-dollar dedicated instances.

**Comment by alphaDev23** [comment]
In the above code, the seed does not shut down until the number of NODE_REPLICAS (which is the total number of nodes plus the seed) have joined and are synced.  To clarify, in the 3+1 example, the value would be set to 4.  If the cluster size is less than the NODE_REPLICAS, then there is a different issue which would need to be manually addressed anyway since the stack did not initiate as defined.

For clarity, NODE_REPLICAS may be set to the actually desired cluster size and the above code modified to account for the same, i.e., change [ "$cluster_size" -lt "$NODE_REPLICAS" ] to [ "$cluster_size" -lt "$NODE_REPLICAS" +1 ].
