### ISSUE TITLE
Mariadb 10.4 and Galera 4

### ISSUE THREAD

**Issue by Jacq** [colinmollenhour/mariadb-galera-swarm#85]
How affects the release of Mariadb 10.4 (that contains GALERA 4) and the new bootstrap options (such as pc.recovery=ON https://galeracluster.com/2019/02/galera-cluster-4-available-for-use-in-the-latest-mariadb-10-4-3-release-candidate/) to the current scripts?
Anyone tested this Mariadb version 10.4.x?
Cheers
Jacq

**Comment by colinmollenhour** [comment]
Looks like some great improvements. I've not tested it, though. Give it a shot and submit a PR! :)

**Comment by colinmollenhour** [comment]
I added a Dockerfile and pushed tags for 10.4. Haven't used in production but the test.sh script passes.
