### ISSUE TITLE
Ngram function doesn't working

### ISSUE THREAD

**Issue by viki-v** [colinmollenhour/mariadb-galera-swarm#88]
please give us a elaborated, information steps to work in mariadb on ngram in Innodb .

- ngram function splits but doesn't gives an exact result in a sorted order
link :https://qiita.com/ArimaRyunosuke/items/d2b3b94f223cb83c463d#%E3%81%BE%E3%81%A8%E3%82%81

above link is ngram function and process ,but i cant understand ..Help me...!

because i want implement these in mariadb galera swarm

**Comment by colinmollenhour** [comment]
Hi viki-v, this is not a place for general MySQL /MariaDb questions, only issues related specifically to the Docker files in this repo.
