### ISSUE TITLE
i am getting error ,but file is in that directory

### ISSUE THREAD

**Issue by viki-v** [colinmollenhour/mariadb-galera-swarm#89]
[centos@ip-172-31-33-86 mariadb-galera-swarm]$ docker build -t mariagalera - < Dockerfile-10.4
Sending build context to Docker daemon  3.072kB
Step 1/12 : FROM mariadb:10.4
 ---> 2f11cf2ec189
Step 2/12 : COPY bin/qpress-11-linux-x64.tar /tmp/qpress.tar
COPY failed: stat /var/lib/docker/tmp/docker-builder579211663/bin/qpress-11-linux-x64.tar: no such file or directory

**Comment by colinmollenhour** [comment]
Strange, I have no idea why you would have that, builds all succeed for me...

**Comment by koelle25** [comment]
Your build command seems strange. Try to use it the standard way (works for me):
`docker build -t mariagalera -f Dockerfile-10.4 .`
