### ISSUE TITLE
Small Help to create docker file, sir

### ISSUE THREAD

**Issue by viki-v** [colinmollenhour/mariadb-galera-swarm#90]
i want to add a mroonga plugin in your, maridb-galera-swarm..  
i trying this but i am getting error on qpress file...
can you create me a dockerfile that working......please..!

mroonga plugin docker file
https://hub.docker.com/r/kazaoki/mariadb-mroonga/dockerfile

**Comment by colinmollenhour** [comment]
Are you trying to build with only the Dockerfile? You need the entire repo to build this image, the Dockerfile alone is not enough.

**Comment by viki-v** [comment]
yes try that also but it didn't works...can you help me to create docker maridb-galera-swarm with mroonga plugin..

**Comment by colinmollenhour** [comment]
I don't think there is any bug in this repo preventing it from being built, it should just be a simple:

```
$ git clone https://github.com/colinmollenhour/mariadb-galera-swarm.git
$ cd mariadb-galera-swarm
$ docker build . -t myimage
```

Then modify the Dockerfile as needed.

Or, create a new Dockerfile based on one of my pre-built images:

```
FROM colinmollenhour/mariadb-galera-swarm:latest
RUN echo "testing"
```

However, this isn't the place for this type of support so I would suggest trying a more help-based community like an IRC channel where there are people that can help you with this type of issue.
