### ISSUE TITLE
Can't install plugin ..Version problem

### ISSUE THREAD

**Issue by viki-v** [colinmollenhour/mariadb-galera-swarm#91]
MariaDB [(none)]> show engines;
+--------------------+---------+--------------------------------------------------------------------------------------------------+--------------+------+------------+
| Engine             | Support | Comment                                                                                          | Transactions | XA   | Savepoints |
+--------------------+---------+--------------------------------------------------------------------------------------------------+--------------+------+------------+
| MRG_MyISAM         | YES     | Collection of identical MyISAM tables                                                            | NO           | NO   | NO         |
| CSV                | YES     | Stores tables as CSV files                                                                       | NO           | NO   | NO         |
| MEMORY             | YES     | Hash based, stored in memory, useful for temporary tables                                        | NO           | NO   | NO         |
| MyISAM             | YES     | Non-transactional engine with good performance and small data footprint                          | NO           | NO   | NO         |
| SEQUENCE           | YES     | Generated tables filled with sequential values                                                   | YES          | NO   | YES        |
| Aria               | YES     | Crash-safe tables with MyISAM heritage                                                           | NO           | NO   | NO         |
| PERFORMANCE_SCHEMA | YES     | Performance Schema                                                                               | NO           | NO   | NO         |
| InnoDB             | DEFAULT | Percona-XtraDB, Supports transactions, row-level locking, foreign keys and encryption for tables | YES          | YES  | YES        |
+--------------------+---------+--------------------------------------------------------------------------------------------------+--------------+------+------------+
8 rows in set (0.00 sec)

MariaDB [(none)]> SET @inst=IF(EXISTS(SELECT * FROM mysql.plugin WHERE NAME='mroonga'),'DO 1', "INSTALL PLUGIN mroonga SONAME 'ha_mroonga'");
Query OK, 0 rows affected (0.00 sec)

MariaDB [(none)]> PREPARE s FROM @inst;
Query OK, 0 rows affected (0.00 sec)
Statement prepared

MariaDB [(none)]> EXECUTE s;
ERROR 1126 (HY000): Can't open shared library 'ha_mroonga.so' (errno: 8, API version for STORAGE ENGINE plugin Mroonga not supported by this version of the server)
MariaDB [(none)]>

**Comment by viki-v** [comment]
And also can't update mariaDB server in bash...is there any way to add plugin inside the mariadb .
Help me Sir,..

**Comment by colinmollenhour** [comment]
Please read docker documentation on how to write a Dockerfile. You can extend the images provided by this project or fork the project and modify the Dockerfiles but this exercise is something I will not be able to assist you with.
