### ISSUE TITLE
Error while buliding ..!

### ISSUE THREAD

**Issue by viki-v** [colinmollenhour/mariadb-galera-swarm#92]
Processing triggers for libc-bin (2.19-18+deb8u10) ...
+ tar -C /usr/local/bin -xf /tmp/qpress.tar qpress
+ chmod +x /usr/local/bin/qpress
+ rm -rf /tmp/qpress.tar /var/cache/apk/* /var/lib/apt/lists/deb.debian.org_debian_dists_jessie-updates_InRelease /var/lib/apt/lists/deb.debian.org_debian_dists_jessie-updates_main_binary-amd64_Packages.gz /var/lib/apt/lists/deb.debian.org_debian_dists_jessie_Release /var/lib/apt/lists/deb.debian.org_debian_dists_jessie_Release.gpg /var/lib/apt/lists/deb.debian.org_debian_dists_jessie_main_binary-amd64_Packages.gz /var/lib/apt/lists/ftp.osuosl.org_pub_mariadb_repo_10.1_debian_dists_jessie_InRelease /var/lib/apt/lists/ftp.osuosl.org_pub_mariadb_repo_10.1_debian_dists_jessie_main_binary-amd64_Packages.gz /var/lib/apt/lists/lock /var/lib/apt/lists/partial /var/lib/apt/lists/repo.percona.com_apt_dists_jessie_InRelease /var/lib/apt/lists/repo.percona.com_apt_dists_jessie_main_binary-amd64_Packages.gz /var/lib/apt/lists/security.debian.org_dists_jessie_updates_InRelease /var/lib/apt/lists/security.debian.org_dists_jessie_updates_main_binary-amd64_Packages.gz
Removing intermediate container 2978795bf2c1
 ---> 1cdfe7ad03d8
Step 4/12 : COPY conf.d/*                /etc/mysql/conf.d/
 ---> 4be85691f936
Step 5/12 : COPY *.sh                    /usr/local/bin/
 ---> 7c7736d47aef
Step 6/12 : COPY bin/galera-healthcheck  /usr/local/bin/galera-healthcheck
 ---> a4a388db55d5
Step 7/12 : COPY primary-component.sql   /
 ---> e3d9bc7c8139
Step 8/12 : RUN set -ex ;    chown -R mysql:mysql /etc/mysql ;    chmod -R go-w /etc/mysql ;    sed -i 's#-p \$progress#-p \$progress-XXX#' /usr/bin/wsrep_sst_mariabackup ;    sed -i 's#-p \$progress#-p \$progress-XXX#' /usr/bin/wsrep_sst_xtrabackup
 ---> Running in 28dc6eadec2e
+ chown -R mysql:mysql /etc/mysql
+ chmod -R go-w /etc/mysql
+ sed -i s#-p \$progress#-p \$progress-XXX# /usr/bin/wsrep_sst_mariabackup
+ sed -i s#-p \$progress#-p \$progress-XXX# /usr/bin/wsrep_sst_xtrabackup
Removing intermediate container 28dc6eadec2e
 ---> 465ad77e58d5
Step 9/12 : EXPOSE 3306 4444 4567 4567/udp 4568 8080 8081
 ---> Running in cd99db80b601
Removing intermediate container cd99db80b601
 ---> 0685d6995309
Step 10/12 : HEALTHCHECK CMD /usr/local/bin/healthcheck.sh
 ---> Running in 1022bf1175da
Removing intermediate container 1022bf1175da
 ---> 180b33a8de2c
Step 11/12 : ENV SST_METHOD=xtrabackup-v2
 ---> Running in b604172efb9d
Removing intermediate container b604172efb9d
 ---> c493e72e1e2c
Step 12/12 : ENTRYPOINT ["start.sh"]
 ---> Running in 09c00204a036
Removing intermediate container 09c00204a036
 ---> 234db40508f1
Successfully built 234db40508f1
Successfully tagged mariagalera:latest

**Comment by viki-v** [comment]
step 8 is not working ...because of that it asking.... plugin-load-add = auth_socket.so..please help me sir
i am working for a long days to add mroonga engine in your galera swarm 
could give me image an particular mroonga repersented mariadb versions


Mroonga Version | Introduced | Maturity
-- | -- | --
7.07 | MariaDB 10.2.11, MariaDB 10.1.29 | Stable
5.04 | MariaDB 10.1.6 | Stable
5.02 | MariaDB 10.0.18, MariaDB 10.1.5 | Stable
5.0 | MariaDB 10.0.17 | Stable
4.06 | MariaDB 10.0.15 | Stable

https://mariadb.com/kb/en/about-mroonga/#how-to-install

**Comment by colinmollenhour** [comment]
Did you try simply extending the built images?

```
FROM colinmollenhour/mariadb-galera-swarm:10.4.11-2020-01-06
RUN apt-get update \
    && apt-get install -y --no-install-recommends --no-install-suggests mariadb-plugin-mroonga
    && rm -rf /tmp/* /var/lib/apt/lists/*
```

I'm not sure why it isn't building offhand but the above is the easiest and then you can continue to track updates easily.

**Comment by viki-v** [comment]
It's Working and Thank You So Much Sir...!
Your Support toward's a developer makes me very happy..!
